# Generated by Django 3.2 on 2021-04-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_salary',
            name='emp_id',
            field=models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to='city.employee'),
        ),
    ]
