# Generated by Django 3.2 on 2021-04-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_emp_salary_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_salary',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id_id', on_delete=django.db.models.deletion.CASCADE, to='city.employee'),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
