# Generated by Django 3.2 on 2021-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20210429_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_salary',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.FloatField(null=True),
        ),
    ]
