# Generated by Django 3.2 on 2021-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_alter_empsalary_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsalary',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
